version: '2.3'

services:
  gpu_tf:
    container_name: gpu_tf
    image: tensorflow/tensorflow:latest-gpu
    ports:
      - 8888:8888
    volumes:
      - ./app:/opt/
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
    command: bash